"""create_schemes_table

Revision ID: 18a734b49ab0
Revises: db15fe3b2bb3
Create Date: 2026-07-02 03:05:28.914179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.app.models.scheme


# revision identifiers, used by Alembic.
revision: str = '18a734b49ab0'
down_revision: Union[str, Sequence[str], None] = 'db15fe3b2bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ministry', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.JSON(), nullable=True),
    sa.Column('states', backend.app.models.scheme.SafeArray(), nullable=True),
    sa.Column('crops', backend.app.models.scheme.SafeArray(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schemes_category'), 'schemes', ['category'], unique=False)
    op.create_index(op.f('ix_schemes_name'), 'schemes', ['name'], unique=False)
    op.add_column('farmer_profiles', sa.Column('market_preferences', sa.JSON(), nullable=True))
    op.add_column('farmer_profiles', sa.Column('scheme_participation', sa.JSON(), nullable=True))
    op.add_column('farms', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('ph', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('nitrogen', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('phosphorus', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('potassium', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('organic_carbon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'organic_carbon')
    op.drop_column('farms', 'potassium')
    op.drop_column('farms', 'phosphorus')
    op.drop_column('farms', 'nitrogen')
    op.drop_column('farms', 'ph')
    op.drop_column('farms', 'longitude')
    op.drop_column('farms', 'latitude')
    op.drop_column('farmer_profiles', 'scheme_participation')
    op.drop_column('farmer_profiles', 'market_preferences')
    op.drop_index(op.f('ix_schemes_name'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_category'), table_name='schemes')
    op.drop_table('schemes')
    # ### end Alembic commands ###
