"""Add farmer profile columns

Revision ID: c36d76997df0
Revises: 9c5593589cd2
Create Date: 2026-04-14 17:58:50.584947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c36d76997df0'
down_revision: Union[str, Sequence[str], None] = '9c5593589cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('land_size_acres', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('crops_grown', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('category', sa.String(), nullable=True))
    op.add_column('users', sa.Column('annual_income', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'annual_income')
    op.drop_column('users', 'category')
    op.drop_column('users', 'crops_grown')
    op.drop_column('users', 'land_size_acres')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    op.drop_column('users', 'district')
    op.drop_column('users', 'state')
    # ### end Alembic commands ###
