"""add_username_to_users

Revision ID: ee34f537eeb1
Revises: f4666ebe4550
Create Date: 2026-06-11 18:17:59.445153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee34f537eeb1'
down_revision: Union[str, Sequence[str], None] = 'f4666ebe4550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add new columns as nullable first
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'BLOCKED', 'DELETED', name='accountstatus'), nullable=True))
    
    # 2. Populate legacy data
    # Copy hashed_password -> password_hash
    op.execute("UPDATE users SET password_hash = hashed_password WHERE password_hash IS NULL AND hashed_password IS NOT NULL")
    op.execute("UPDATE users SET password_hash = 'not-used' WHERE password_hash IS NULL")
    
    # Use email as username fallback (since phone_number/phone can be NULL or duplicate)
    op.execute("UPDATE users SET username = COALESCE(email, 'user_' || id) WHERE username IS NULL")
    
    # Default status to ACTIVE
    op.execute("UPDATE users SET status = 'ACTIVE' WHERE status IS NULL")
    
    # Generate unique fallback phone numbers for users without any phone number
    op.execute("UPDATE users SET phone_number = '+91999999' || id WHERE phone_number IS NULL")
    
    # 3. Enforce NOT NULL constraints now that data is populated
    op.alter_column('users', 'username', nullable=False)
    op.alter_column('users', 'password_hash', nullable=False)
    op.alter_column('users', 'status', nullable=False)
    
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'phone_verified_at')
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('account_status', postgresql.ENUM('ACTIVE', 'SUSPENDED', 'BLOCKED', 'DELETED', name='accountstatus'), server_default=sa.text("'ACTIVE'::accountstatus"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_phone_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'status')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
