"""add_farm_management

Revision ID: f20af12cc678
Revises: c36d76997df0
Create Date: 2026-06-03 21:39:39.751964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f20af12cc678'
down_revision: Union[str, Sequence[str], None] = 'c36d76997df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types for existing table column additions/alterations
    sa.Enum('ENGLISH', 'HINDI', name='language').create(op.get_bind())
    sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender').create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.Enum('ALLUVIAL', 'BLACK', 'RED', 'LATERITE', 'SANDY', 'CLAYEY', 'LOAMY', 'OTHER', name='soiltype'), nullable=False),
    sa.Column('irrigation_source', sa.Enum('BOREWELL', 'CANAL', 'RAIN_FED', 'DRIP', 'SPRINKLER', 'OTHER', name='irrigationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_index(op.f('ix_farms_user_id'), 'farms', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('PEST_ALERT', 'MARKET_ALERT', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('crop_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.Column('crop_variety', sa.String(), nullable=True),
    sa.Column('season', sa.Enum('KHARIF', 'RABI', 'ZAID', name='cropseason'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('current_stage', sa.Enum('SEEDING', 'GERMINATION', 'VEGETATIVE', 'FLOWERING', 'FRUITING', 'MATURITY', 'HARVEST_READY', name='cropstage'), nullable=False),
    sa.Column('area_under_crop', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='cropcyclestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_cycles_farm_id'), 'crop_cycles', ['farm_id'], unique=False)
    op.create_index(op.f('ix_crop_cycles_id'), 'crop_cycles', ['id'], unique=False)
    op.create_table('crop_journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_cycle_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('SOWING', 'IRRIGATION', 'FERTILIZER', 'PESTICIDE', 'OBSERVATION', 'HARVEST', name='journalentrytype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_journal_entries_crop_cycle_id'), 'crop_journal_entries', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_crop_journal_entries_id'), 'crop_journal_entries', ['id'], unique=False)
    op.create_table('pest_detection_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crop_cycle_id', sa.Integer(), nullable=True),
    sa.Column('disease_name', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('YOLO', 'MANUAL', 'CHATBOT', name='pestdetectionsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pest_detection_histories_crop_cycle_id'), 'pest_detection_histories', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_pest_detection_histories_id'), 'pest_detection_histories', ['id'], unique=False)
    op.create_index(op.f('ix_pest_detection_histories_user_id'), 'pest_detection_histories', ['user_id'], unique=False)
    op.add_column('users', sa.Column('village', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.Enum('ENGLISH', 'HINDI', name='language'), server_default='ENGLISH', nullable=False))
    op.add_column('users', sa.Column('is_onboarded', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'),
               existing_nullable=True,
               postgresql_using="CASE WHEN UPPER(gender) = 'MALE' THEN 'MALE'::gender WHEN UPPER(gender) = 'FEMALE' THEN 'FEMALE'::gender WHEN UPPER(gender) = 'OTHER' THEN 'OTHER'::gender ELSE NULL END")
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    
    # Fix null updated_at values before setting nullable=False
    bind = op.get_bind()
    bind.execute(sa.text("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL"))
    
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
               
    # Data migration from crops_grown ARRAY to crop_cycles
    users = bind.execute(sa.text("SELECT id, name, crops_grown FROM users")).fetchall()
    for user_id, user_name, crops_grown in users:
        if crops_grown:
            if isinstance(crops_grown, list):
                crops = crops_grown
            elif isinstance(crops_grown, str):
                crops = crops_grown.strip("{}").split(",")
                crops = [c.strip('" ') for c in crops if c.strip()]
            else:
                crops = []

            if crops:
                # Insert default farm
                farm_result = bind.execute(sa.text(
                    "INSERT INTO farms (user_id, farm_name, soil_type, irrigation_source, created_at) "
                    "VALUES (:user_id, :farm_name, 'OTHER', 'OTHER', NOW()) RETURNING id"
                ), {
                    "user_id": user_id,
                    "farm_name": f"{user_name}'s Farm"
                })
                farm_row = farm_result.fetchone()
                if farm_row:
                    farm_id = farm_row[0]
                    for crop_name in crops:
                        bind.execute(sa.text(
                            "INSERT INTO crop_cycles (farm_id, crop_name, season, current_stage, status, created_at, updated_at) "
                            "VALUES (:farm_id, :crop_name, 'KHARIF', 'SEEDING', 'ACTIVE', NOW(), NOW())"
                        ), {
                            "farm_id": farm_id,
                            "crop_name": crop_name
                        })

    op.drop_column('users', 'crops_grown')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('crops_grown', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'is_onboarded')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'village')
    op.drop_index(op.f('ix_pest_detection_histories_user_id'), table_name='pest_detection_histories')
    op.drop_index(op.f('ix_pest_detection_histories_id'), table_name='pest_detection_histories')
    op.drop_index(op.f('ix_pest_detection_histories_crop_cycle_id'), table_name='pest_detection_histories')
    op.drop_table('pest_detection_histories')
    op.drop_index(op.f('ix_crop_journal_entries_id'), table_name='crop_journal_entries')
    op.drop_index(op.f('ix_crop_journal_entries_crop_cycle_id'), table_name='crop_journal_entries')
    op.drop_table('crop_journal_entries')
    op.drop_index(op.f('ix_crop_cycles_id'), table_name='crop_cycles')
    op.drop_index(op.f('ix_crop_cycles_farm_id'), table_name='crop_cycles')
    op.drop_table('crop_cycles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_farms_user_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
